### ISSUE TITLE
java.lang.NoSuchMethodError: No static method toDouble-impl 에러

### ISSUE THREAD

**Issue by chanjungkim** [iamport/iamport-manual#50]
M1Pro 환경에서 프로젝트를 켜니까 다음과 같이 에러가 발생했습니다.

구현부:
```
import android.app.Application
import com.iamport.sdk.domain.core.Iamport

class MyApplication:Application() {
  override fun onCreate() {
    super.onCreate()

    Iamport.create(this)
  }
}
```

발생한 에러:
```
    java.lang.NoSuchMethodError: No static method toDouble-impl(JLjava/util/concurrent/TimeUnit;)D in class Lkotlin/time/Duration; or its super classes (declaration of 'kotlin.time.Duration' appears in /data/app/com.example-WGmxxg2pcjuM-HxQu-f9_Q==/base.apk!classes14.dex)
        at org.koin.core.time.MeasureKt.measureDuration(Measure.kt:32)
        at org.koin.core.KoinApplication.modules(KoinApplication.kt:59)
        at com.iamport.sdk.domain.core.Iamport$createWithKoin$1.invoke(Iamport.kt:109)
        at com.iamport.sdk.domain.core.Iamport$createWithKoin$1.invoke(Iamport.kt:106)
        at org.koin.core.context.GlobalContext.startKoin(GlobalContext.kt:64)
        at org.koin.core.context.DefaultContextExtKt.startKoin(DefaultContextExt.kt:31)
        at com.iamport.sdk.domain.core.Iamport.createWithKoin(Iamport.kt:106)
        at com.iamport.sdk.domain.core.Iamport.createWithKoin$default(Iamport.kt:101)
        at com.iamport.sdk.domain.core.Iamport.create(Iamport.kt:94)
        at com.example.MyApplication.onCreate(MyApplication.kt:10)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by chanjungkim** [comment]
https://github.com/InsertKoinIO/koin/issues/1188 혹시 코인과 관련된 에러인지..

**Comment by kjh5833** [comment]
https://github.com/iamport/iamport-android/issues/47

위 이슈와 같습니다.
